### ISSUE TITLE
Fixed the Encryption Mechanism for Secure Message creation

### ISSUE THREAD

**Issue by alvin-reyes** [NemProject/csharp2nem#2]
TransferTransaction seems to only support Plain Messages. As discussed with @kodty , the encryption is broken for creating secured messages hence this feature is not active. 

This needs to be fixed for secure message transactions.

**Comment by kodty** [comment]
resolved.

to decrypt message returned, use:
`using  CSharp2nem.CryptographicFunctions` `Encryption.Decode(ar.Content.data[0].transaction.message.payload, new PrivateKey("key"), "publicKey");`

to encrypt message when sending a transaction:
set `TransferTransactionData.Encrypted = true;`
