### ISSUE TITLE
BeginSignatureTransactionAsync didn't work

### ISSUE THREAD

**Issue by CryptoMikan** [NemProject/csharp2nem#3]
I tried multisig-transaction by `BeginSignatureTransactionAsync` but failed.

Expected result: sign to transaction and xem transaction success.
Actual result: `WebException: The remote server returned an error: (404) Not Found.`

My sample code is below (This is written for Unity).

```
        IEnumerator signCor()
        {
            PrivateKeyAccountClientFactory accountFactory = new PrivateKeyAccountClientFactory();
            PrivateKeyAccountClient accClient = accountFactory.FromPrivateKey(SignerWallet2PrivateKey);

            var sigData = new MultisigSignatureTransactionData
            {
                MultisigAddress = MultisigWalletAddress,
                TransactionHash = transactionHash
            };

            var result = accClient.BeginSignatureTransactionAsync(sigData);

            Debug.Log("waiting..");
            yield return new WaitWhile(() => !result.IsCompleted);

            var response = accClient.EndTransaction(result);
            Debug.Log(response.ToLog());
        }
```

Signature is succeeded on NanoWallet.

**Comment by kodty** [comment]
If the multisig address is lowercase, it results in different hex value and therefore triggers that error, by the looks of things. other than that, i cant seem to find an issue with the code. if that isnt the issue, please let me know exactly what test data your using so i can try replicate.

**Comment by kodty** [comment]
try 

`Connection con = new Connection();
               con.SetTestnet();
               
               PrivateKeyAccountClientFactory accountFactory = new PrivateKeyAccountClientFactory(con);
               PrivateKeyAccountClient accClient = accountFactory.FromPrivateKey(publicKey);
               
               var sigData = new MultisigSignatureTransactionData
               {
                   MultisigAddress = new Address(addressInUpperCase),
                   TransactionHash = transactionHashString
               };

            var d = accClient.EndTransaction(accClient.BeginSignatureTransactionAsync(sigData));

            Console.WriteLine(d.Message);

            Console.ReadLine();`

note: the error response needs to be seriously improved, just havnt had time. If you use fiddler to pick out outgoing http requests, it will also catch any errors and give some extra detail about what is actually wrong. in some cases it will give error 404, and the extra data fiddler picks up might say invalid address or something to that effect. also apologies for the late reply.

**Comment by kodty** [comment]
Please let me know if this is solved. thanks

**Comment by CryptoMikan** [comment]
I'm sorry for being late.
The code you sent to me showed same error.
And the data picked up with fiddler showed response below.

```
POST http://62.75.251.134:7890/transaction/announce HTTP/1.1
Accept: application/json
Content-Type: application/json
Content-Length: 442
Expect: 100-continue
Host: 62.75.251.134:7890

{"data":"021000000100006824A9700520000000564CAD75EDD7D85CE54FDF7B097FDCA7521D7C24EA3E39937145C0B7E9D14D04F0490200000000003CB7700524000000200000003D242590BBAA0E78992EFBFDEBF915264C4084A1DAB58F44F155C0F7E40420072800000031636264626264656639303338653732303062363837636539376464626664646131323239356466","signature":"B3E5054B48025C1D4C04D330419896AB27801B10743D9EDA79C56FB9F31901E4D8C25FB314A067F717BE840FF5F75C938EF83D57B6282AEA486C6D05DFCD480D"}


HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Content-Type: application/json
Transfer-Encoding: chunked
Server: Jetty(9.2.11.v20150529)

9D
{"timeStamp":91269412,"error":"Not Found","message":"invalid address '1CBDBBDEF9038E7200B687CE97DDBFDDA12295DF' (org.nem.core.model.Address)","status":404}

0
```

**Comment by kodty** [comment]
excerpt: invalid address '1CBDBBDEF9038E7200B687CE97DDBFDDA12295DF'

this is what you need to investigate. how are you entering the address? how are you creating it? it should start with T for testnet or N for mainnet.

**Comment by CryptoMikan** [comment]
sorry, it is public key of multisig account.
but even change it to multisig address, the error appeared.

```
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Content-Type: application/json
Server: Jetty(9.2.11.v20150529)
Content-Length: 157

{"timeStamp":91273471,"error":"Not Found","message":"invalid address 'TDMLK5YCLNVMWCKYAWKTPJARTPDBEMQ2RSQVG23F' (org.nem.core.model.Address)","status":404}
```

**Comment by kodty** [comment]
your sending a testnet transaction to main net. 

http://62.75.251.134:7890/node/info

networkId: 104 - which is main net.

are you 1) setting connection to test net 2) passing the connection instance into PrivateKeyAccountClientFactory constructor?

**Comment by CryptoMikan** [comment]
>2) passing the connection instance into PrivateKeyAccountClientFactory constructor?

this is the cause! I'm sorry to have inconvenienced you.

**Comment by kodty** [comment]
No problem at all. :) glad its resolved.
